# Generated by Django 2.1.4 on 2019-01-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190102_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='id',
        ),
        migrations.AlterField(
            model_name='todo',
            name='item',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
